apiVersion: v1
kind: ServiceAccount
metadata:
  name: plancia
  namespace: plancia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plancia
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plancia
  namespace: navarcos
subjects:
  - kind: ServiceAccount
    name: plancia
    namespace: plancia
roleRef:
  kind: ClusterRole
  name: plancia
  apiGroup: rbac.authorization.k8s.io