apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-environment
  namespace: plancia
data:
  config.js: |
    window.ENVIRONMENT = 
    {
    "SERVER_URL": "https://plancia-api.172.20.0.2.nip.io/api/v1",
    "POLLING_INTERVAL": 5000,
    "KEYCLOAK_URL": "https://keycloak.172.20.0.2.nip.io",
    "KEYCLOAK_REALM": "Navarcos",
    "KEYCLOAK_CLIENT_ID": "plancia",
    }