apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-environment
  namespace: plancia
data:
  config.js: |
    window.ENVIRONMENT = 
    {
    "SERVER_URL": "https://plancia-api${NAVARCOS_DOMAIN_SUFFIX}/api/v1",
    "POLLING_INTERVAL": 5000,
    "KEYCLOAK_URL": "https://keycloak${NAVARCOS_DOMAIN_SUFFIX}",
    "KEYCLOAK_REALM": "Navarcos",
    "KEYCLOAK_CLIENT_ID": "plancia",
    }