kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-csi-waitforfirstconsumer-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  datastoreurl: "${VSPHERE_DATASTOREURL}"
reclaimPolicy: Delete
